version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DSN=postgresql://gstuser:gstpassword@postgres:5432/gstintelligence
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: gstintelligence
      POSTGRES_USER: gstuser
      POSTGRES_PASSWORD: gstpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
      
volumes:
  postgres_data: